name: Pet Store Collection Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Newman and HTML Reporter
        run: |
          npm install newman newman-reporter-htmlextra

      - name: Make Directory for Results
        run: mkdir -p testResults

      - name: Run POSTMAN Collection
        run: |
          npx newman run petstore.collection.json -r htmlextra \
            --reporter-htmlextra-export testResults/htmlreport.html \
            --reporter-htmlextra-darkTheme || true

      - name: Output the Run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults

      - name: List node_modules
        run: |
          echo "Contents of node_modules:"
          ls -R node_modules

      - name: Prepare Assets for GitHub Pages
        run: |
          mkdir output
          mv testResults/htmlreport.html output/
          cp -r node_modules/newman-reporter-htmlextra/html output/ || echo "HTML assets not found"
          echo 'index.html' > output/.nojekyll
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add output
          git commit -m 'Deploy Pet Store Newman report' || echo "No changes to commit"
          git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:gh-pages
