name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Newman and HTML Reporter
        run: |
          npm install newman newman-reporter-htmlextra

      - name: Make Directory for Results
        run: mkdir -p testResults

      - name: List Repository Contents
        run: |
          echo "Contents of the repository:"
          ls -la

      - name: Run POSTMAN Collection
        run: |
          npx newman run petstore.collection.json -r htmlextra \
            --reporter-htmlextra-export testResults/htmlreport.html \
            --reporter-htmlextra-darkTheme || true

      - name: Output the Run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults

      - name: Prepare Deployment Directory
        run: |
          mkdir -p output
          mv testResults/htmlreport.html output/  
          echo 'index.html' > output/.nojekyll 
  
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
      
      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          # Check if report is generated
          if [ -f "testResults/htmlreport.html" ]; then
            mv testResults/htmlreport.html index.html  # Rename to index.html
            echo '.nojekyll' > .nojekyll  # Prevent Jekyll from processing
            git add index.html .nojekyll
            git commit -m 'Deploy Newman Report to GitHub Pages'
            git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Ola793/Postman-newman-ghActions gh-pages
          else
            echo "Newman report not found!"
            exit 1
          fi
  
  
